### ISSUE TITLE
Gracefully handle comment blocks with lines that start with the word "Styleguide" but aren't KSS sections.

### ISSUE THREAD

**Issue by benknight** [seanbrant/pykss#4]
This is rare, but this case should probably be handled explicitly instead of an an uncaught exception.

```
/**
 * Styleguide
 */
```

Error: `AttributeError: 'NoneType' object has no attribute 'groups'`

Location: `pykss/section.py in parse, line 44`

**Comment by seanbrant** [comment]
Thanks for pointing this out, I've ran into this a few times myself. This can happen anytime you forget a reference so not sure if it should skip whole block or try to do something clever and assign some automatic reference number. I'm leaning towards just skipping the block and possibly outputting a warning to stdout. Thoughts?

**Comment by benknight** [comment]
I think it's fair to expect that anything that doesn't match "Styleguide [reference]" is just ignored by the parser, so long as it's sufficiently clear to developers that this is the format the parser expects to find.  I'd personally avoid doing any kind of magic, such as automatically assigning a section.  This also doesn't address the case where an author may begin a line with word "Styleguide" but does not intend for it to be picked up by the parser.  E.g. "Styleguide specifies that..." or something like that.  (This is actually how I ran into the issue.)

What does the Ruby implementation do?  I would probably look to maintain as much parity as possible with the Ruby implementation for anything from features to parsing errors.

**Comment by seanbrant** [comment]
The ruby version seems to just ignore it [1]. Do you by chance have a failing test case?

[1] https://github.com/kneath/kss/blob/master/lib/kss/section.rb#L83

**Comment by benknight** [comment]
I believe the simple example I provided in this issue's description being present in a CSS files in the file tree will cause the error I described.

Are you unable to reproduce?
