### ISSUE TITLE
Django hanging on {% styleguideblock styleguide %} tag

### ISSUE THREAD

**Issue by sepd** [seanbrant/pykss#8]
I've been working my way through incorporating pykss into my django implementation, but when I request the styleguide, the browser hangs in trying to connect with "localhost". I've looked into the python, specifically pykss/contrib/django/views.py 'context' variable and python seems to hang on context['styleguide'].sections. Has anyone else had this problem, or knows what's wrong and how I can solve it?

Thanks in advance!

**Comment by sepd** [comment]
Issue was on my end and not related to pykss.

**Comment by seanbrant** [comment]
Glad you figured it out!
